server:
  port: 8100

spring:
  application:
    name: smarthint-backend

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cliente-service
      username: admin
      password: admin
      authentication-database: admin
      auto-index-creation: true

  redis:
    host: localhost
    port: 6379
    
springdoc:
  swagger-ui:
    path: documentacao